-- ================================================================
-- ARQVERTICE STUDIO
-- MIGRATION: 0020_quantities_and_calculation_memory.sql
-- VERSÃO: E03 — SISTEMA DE QUANTITATIVOS E MEMÓRIA DE CÁLCULO
-- ================================================================

-- Criação das estruturas caso não existam
\ir ../schema/25_quantities_and_calculation_memory.sql

-- Carga de Seeds Piloto de Quantitativos para o Projeto Praia (prj-praia-01)
-- Materiais: Piso Porcelanato na Sala e Circulação, Travertino na Cozinha, Painel Ripada na Sala
INSERT INTO project_quantities (
  id,
  project_id,
  environment_id,
  material_id,
  product_id,
  item_name,
  category,
  application,
  base_quantity,
  unit,
  loss_percentage,
  final_quantity,
  technical_quantity,
  formula_text,
  formula_expression,
  has_packaging,
  packaging_coverage,
  packaging_unit,
  purchasing_quantity,
  packaging_formula,
  rounding_rule,
  decimal_places,
  origin_type,
  source_type,
  source_file_ref,
  revit_element_id,
  revit_category,
  is_ai_estimate,
  status,
  approval_level,
  notes,
  target_displays,
  include_in_moodboard,
  version_code,
  created_by,
  created_at,
  updated_at
) VALUES 
(
  'qty-praia-sala-piso-01',
  'prj-praia-01',
  'env-living-01',
  'mat-praia-piso-01',
  'prod-portobello-nord-120',
  'Porcelanato Nord Cement 120x120 Nat',
  'PISO',
  'PISO',
  40.0000,
  'm²',
  10.00,
  44.0000,
  44.0000,
  '40,00 m² × 1,10 (perda de 10%) = 44,00 m²',
  '40.00 * 1.10 = 44.00',
  TRUE,
  2.1600,
  'caixa',
  21.0000,
  'Teto(44,00 m² ÷ 2,16 m²/cx) = 21 caixas (45,36 m² efetivos)',
  'CEIL',
  2,
  'MEASURED',
  'PROJECT_DATA',
  'Planta_Baixa_Executiva_R02.dwg',
  'REV-FL-10029',
  'Floors',
  FALSE,
  'APPROVED',
  'QUANTITY_APPROVED',
  'Área base extraída do levantamento executivo cadastrado.',
  ARRAY['ficha', 'prancha', 'relatorio', 'moodboard'],
  TRUE,
  'V01',
  'Eduardo Marques',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'qty-praia-coz-bancada-01',
  'prj-praia-01',
  'env-cozinha-01',
  'mat-praia-bancada-01',
  'prod-travertino-navona',
  'Mármore Travertino Navona Levigado',
  'BANCADA',
  'BANCADA',
  6.5000,
  'm²',
  5.00,
  6.8250,
  6.8250,
  '6,50 m² × 1,05 (perda de 5%) = 6,83 m²',
  '6.50 * 1.05 = 6.825',
  FALSE,
  NULL,
  NULL,
  6.8300,
  NULL,
  'ROUND',
  2,
  'CALCULATED',
  'PROJECT_DATA',
  'Detalhamento_Bancada_Ilha_V03.pdf',
  NULL,
  NULL,
  FALSE,
  'APPROVED',
  'QUANTITY_APPROVED',
  'Bancada em ilha com cuba esculpida e frontão de 15cm.',
  ARRAY['ficha', 'relatorio', 'moodboard'],
  TRUE,
  'V01',
  'Eduardo Marques',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'qty-praia-sala-painel-01',
  'prj-praia-01',
  'env-living-01',
  NULL,
  NULL,
  'Painel Ripada Madeira Freijó Natural',
  'MARCENARIA',
  'PAINEL',
  12.5000,
  'm²',
  15.00,
  14.3750,
  14.3750,
  '12,50 m² × 1,15 (perda de 15% marcenaria) = 14,38 m²',
  '12.50 * 1.15 = 14.375',
  FALSE,
  NULL,
  NULL,
  14.3800,
  NULL,
  'ROUND',
  2,
  'ESTIMATED_BY_AI',
  'VISUAL_ESTIMATE',
  NULL,
  NULL,
  NULL,
  TRUE,
  'ESTIMATED',
  'QUANTITY_ESTIMATED',
  'Estimativa preliminar baseada no render. Requer conferência in loco antes do corte.',
  ARRAY['ficha', 'relatorio'],
  FALSE,
  'V01',
  'AI Vision Estimator',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT (id) DO NOTHING;
